// Generated by LiveScript 1.3.1
var koa, cors, json, send, log, routed, parsed, index, videos, tracks, uploader, registrar, authenticator, app;
koa = require('koa');
cors = require('koa-cors');
json = require('koa-json');
send = require('koa-send');
log = require('koa-logger');
routed = require('koa-router');
parsed = require('koa-better-body');
index = require('./middleware/index');
videos = require('./middleware/videos');
tracks = require('./middleware/tracks');
uploader = require('./middleware/upload');
registrar = require('./middleware/registrar');
authenticator = require('./middleware/authenticator');
app = koa();
app.use(cors());
app.use(log());
app.use(json());
app.use(routed(app));
app.use(function*(){
  yield send(this, this.path, {
    index: 'index.html',
    root: __dirname + '/public'
  });
});
app.get('/form', index).get('/videos', videos).get('/tracks', tracks).post('/register', parsed(), registrar).post('/authenticate', parsed(), authenticator).post('/upload', parsed({
  multipart: true
}), uploader);
app.listen(3000);