// Generated by LiveScript 1.3.1
var koa, log, routed, parsed, index, registrar, authenticator, app;
koa = require('koa');
log = require('koa-logger');
routed = require('koa-router');
parsed = require('koa-better-body');
index = require('./middleware/index');
registrar = require('./middleware/registrar');
authenticator = require('./middleware/authenticator');
app = koa();
app.use(log());
app.use(routed(app));
app.get('/', index).post('/register', parsed(), registrar).post('/authenticate', parsed(), authenticator);
app.listen(3000);