// Generated by LiveScript 1.3.1
var koa, json, log, routed, parsed, index, uploader, registrar, authenticator, app;
koa = require('koa');
json = require('koa-json');
log = require('koa-logger');
routed = require('koa-router');
parsed = require('koa-better-body');
index = require('./middleware/index');
uploader = require('./middleware/upload');
registrar = require('./middleware/registrar');
authenticator = require('./middleware/authenticator');
app = koa();
app.use(log());
app.use(json());
app.use(routed(app));
app.get('/', index).post('/register', parsed(), registrar).post('/authenticate', parsed(), authenticator).post('/upload', parsed({
  multipart: true
}), uploader);
app.listen(3000);