// Generated by LiveScript 1.3.1
var _, jwt, reheat, bcrypt;
require('../models/user');
_ = require('lodash');
jwt = require('koa-jwt');
reheat = require('reheat');
bcrypt = require('co-bcrypt');
module.exports = function*(next){
  var name, password, users, user, profile, secret, token;
  name = this.request.body.fields.username;
  password = this.request.body.fields.password;
  users = yield reheat.getModel('user').collection.findAll({
    where: {
      username: name
    }
  });
  user = users.find(function(usr){
    return name === usr.get('username');
  });
  if (user) {
    if (yield bcrypt.compare(password, user.get('password'))) {
      profile = _.clone(user.toJSON());
      delete profile.password;
      secret = "victoria's_secret";
      token = jwt.sign(profile, secret);
      this.body = {
        token: token
      };
    }
  }
};