// Generated by LiveScript 1.3.1
module.exports = function*(next){
  this.set('Content-Type', 'text/html');
  this.body = '\'\n<!doctype html>\n<html>\n  <body>\n    <div>\n      <form action="/authenticate" method="post">\n        <input type="text" name="name" placeholder="username"><br>\n        <input type="password" name="password" placeholder="password"><br>\n        <button type="submit">submit</button>\n      </form>\n    </div>\n    <div>\n      <form action="/register" method="post">\n        <input type="text" name="user_name" placeholder="username"><br>\n        <input type="text" name="first_name" placeholder="first name"><br>\n        <input type="email" name="email" placeholder="email"><br>\n        <input type="password" name="password" placeholder="password"><br>\n        <button type="submit">submit</button>\n      </form>\n    </div>\n  </body>\n</html>';
  yield next;
};