// Generated by LiveScript 1.3.1
var joi, _, oqps, ords, ordr, invoic, oauth;
joi = require('joi');
_ = require('lodash');
oqps = require('../schema/oqp');
ords = require('../schema/ord');
ordr = require('../models/order');
invoic = require('../models/invoice');
oauth = require('../meddleware/config').oauth;
module.exports = function*(next){
  var octx, prd_valid, dafaults, oqp_valid, order, inv;
  octx = {
    pesapal_request_data: this.request.body.fields
  };
  prd_valid = false;
  joi.validate(octx.pesapal_request_data, ords, function(err, val){
    return prd_valid = true;
  });
  if (!prd_valid) {
    throw new Error('pesapal request data is invalid');
  }
  dafaults = {
    type: 'MERCHANT',
    reference: uuid()
  };
  _.assign(octx.pesapal_request_data, defaults);
  oqp_valid = false;
  joi.validate(oauth, oqps, function(err, val){
    return oqp_valid = true;
  });
  if (!oqp_valid) {
    throw new Error('order query parameters are invalid');
  }
  _.assign(octx, oauth);
  order = new ordr(octx);
  inv = new invoic(order).tojson();
  yield inv.save();
  res.redirect(order.url);
  next;
};