// Generated by LiveScript 1.3.1
var model;
model = require('../models/user');
module.exports = function*(next){
  var user;
  user = new model(this.request.body.fields);
  this.body = yield user.save();
};