// Generated by LiveScript 1.3.1
var _, filesystem, model;
_ = require('lodash');
filesystem = require('mz/fs');
model = require('../models/sample');
module.exports = function*(next){
  var upload, path, file, instance, attachment;
  upload = _.first(_.values(this.request.body.files));
  path = _.values(_.pick(upload, "path")).toString();
  file = yield filesystem.readFile(path);
  instance = _.assign(_.omit(upload, "path"), {
    'file': file
  });
  attachment = yield new model(instance.toJSON()).save();
  this.body = _.omit(attachment.toJSON(), "file");
};