// Generated by LiveScript 1.3.1
var faker;
faker = require('faker');
module.exports = function*(next){
  var videos, shoot, i$, i;
  videos = [];
  shoot = function(){
    return {
      id: faker.random.uuid(),
      title: faker.company.bs(),
      artist: faker.name.findName(),
      avatar: faker.internet.avatar()
    };
  };
  for (i$ = 1; i$ <= 20; ++i$) {
    i = i$;
    videos.push(shoot());
  }
  this.body = videos;
  yield next;
};