// Generated by LiveScript 1.3.1
var reheat;
reheat = require('reheat');
module.exports = reheat.defineModel('order', {
  softDelete: true,
  tableName: 'orders',
  connection: new reheat.Connection()
}, {
  beforeCreate: function(done){
    return done();
  }
});