// Generated by LiveScript 1.3.1
var _;
_ = require('lodash');
module.exports = {
  get: function(prop){
    if (_.has(this.ctx, prop)) {
      return _.values(_.pick(this.ctx, prop)).toString();
    }
    throw new Error('you only get what you set');
  },
  set: function(prop){
    if (!_.isPlainObject(prop)) {
      throw new Error('i object pass in an object');
    }
    return _.merge(this.ctx, prop);
  }
};