// Generated by LiveScript 1.3.1
var reheat, con, model;
reheat = require('reheat');
con = new reheat.Connection({
  db: 'dev'
});
model = reheat.defineModel('sample', {
  tableName: 'samples',
  connection: con
}, {});
module.exports = model;