// Generated by LiveScript 1.3.1
var reheat, bcrypt, con, model;
reheat = require('reheat');
bcrypt = require('bcrypt');
con = new reheat.Connection({
  db: 'dev'
});
model = reheat.defineModel('user', {
  tableName: 'users',
  connection: con
}, {
  beforeCreate: function(done){
    var password, hash;
    password = this.get('password');
    hash = bcrypt.hashSync(password, 10);
    this.unset('password');
    this.set({
      password: hash
    });
    return done();
  }
});
module.exports = model;